### ISSUE TITLE
Feature request: Sweep all / prevent dust

### ISSUE THREAD

**Issue by seth586** [muun/falcon#1]
I recently did a transaction in an attempt to sweep all my funds, but in the end created a dust UTXO of ~600 satoshis.

This is bad hygiene for the UTXO set and bitcoin's blockchain.

I'd recommend the insufficient funds popup recommend an amount to prevent the creation of dust when trying to spend all of your bitcoin.

**Comment by champo** [comment]
Hi! I'm not sure I understand what happened. What I get is:
 - You sent some sats into Muun
 - Sweeped your funds into another wallet?
 - That sweep was for ~600 sats due to a higher than needed fee?

It would be really useful for us to have some more data to debug this issue. If you don't want to share it in this setting, you can reach us at contact@muun.com or by Twitter @muunwallet.

Thanks!

**Comment by mdb1** [comment]
Close due to inactivity.
@seth586 feel free to reopen if you have further questions!
