### ISSUE TITLE
LN invoice time constraint makes Muun unsuitable for (web)shops

### ISSUE THREAD

**Issue by annetdeboer** [muun/falcon#2]
If I want to pay with Lightning in webshops or brick and mortar stores it's very common to get an invoice with a timespan of 10 minutes. Within this time, the invoice should be paid, because the amount of bitcoins needed are calculated on the current Bitcoin price (the price of the products are in local currency).
When I scan such an invoice with Muun it tells me "This payment needs a longer expiration time"
and "We suggest an expiration time of 1 hour or more"

This makes Muun unsuitable to be used when paying for products in above situations. Was this time constraint intentionally?
Can this be changed so that Muun is capable of paying invoices even when the invoice almost expires?

**Comment by mdb1** [comment]
Hey @annetdeboer ! Thanks for reporting this issue.

Currently users can pay lightning invoices using Muun because we are using [Submarine Swaps](https://medium.com/muunwallet/a-closer-look-at-submarine-swaps-in-the-lightning-network-4417a2e8f93c) to fulfill the payments. This implies that there is going to be an **on-chain transaction**.

When making a lightning payment we need to decide if it will be instantly payed (`0-conf` for the on-chain tx) or if we are going to wait to see the tx on a block (`1-conf`). The way we decide between those options depends:
1. On the **amount** of the swap
2. If one of the inputs has **Replace by Fee (RBF)** enabled, the swap will be always `1-conf`, regardless the amount.

Since we need the `1-conf` swaps to be payed as soon as possible, the fee we select for them is the `next block` fee, and it's way higher than `0-conf` swaps.

### Expiration times needed:
- For `0-conf` swaps we require **at least 1 minute** left until the invoice expires.
- For `1-conf` swaps we require approximately **14 minutes** left until the invoice expires, so we can see the funding transaction in the next block.

**It's in our roadmap** to improve this rules, so the users can have a better **experience** when paying for high amount invoices.

Let us know if you have any more doubts or suggestions! We're all about hearing what our users have to say.

**Comment by mdb1** [comment]
Close due to inactivity. 
@annetdeboer feel free to reopen if you have further questions!

**Comment by annetdeboer** [comment]
Hi @mdb1 sorry I never replied. Your explanation was much appreciated though. I have tried Muun again for a LN payment (for coffee) and this time it did work but to be honest, the first try was also a coffee if I'm right, or something small (which is why I used LN) so I can't really recall what the exact difference was. 
I hope some time in the future swapping is not needed anymore though :) would be nice if LN payments through Muun are also free (and instant ;) 
Keep up the good work! Cheers ~
